version: '3.8'

services:
  # Open WebUI Service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - llm_network

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    command: sh -c "ollama pull deepseek-r1:1.5b && ollama pull all-minilm:latest && ollama serve"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - llm_network
    # Uncomment the following lines to enable GPU support (if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  llm_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  open_webui_data:
    driver: local
